// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.petclinic.domain;

import com.springsource.petclinic.domain.PetDataOnDemand;
import com.springsource.petclinic.domain.Visit;
import java.util.List;
import java.util.Random;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

privileged aspect VisitDataOnDemand_Roo_DataOnDemand {
    
    declare @type: VisitDataOnDemand: @Component;
    
    private Random VisitDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Visit> VisitDataOnDemand.data;
    
    @Autowired
    private PetDataOnDemand VisitDataOnDemand.petDataOnDemand;
    
    public Visit VisitDataOnDemand.getNewTransientVisit(int index) {
        com.springsource.petclinic.domain.Visit obj = new com.springsource.petclinic.domain.Visit();
        obj.setDescription("description_" + index);
        obj.setPet(petDataOnDemand.getRandomPet());
        obj.setVet(null);
        obj.setVisitDate(new java.util.Date(new java.util.Date().getTime() - 10000000L));
        return obj;
    }
    
    public Visit VisitDataOnDemand.getSpecificVisit(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Visit obj = data.get(index);
        return Visit.findVisit(obj.getId());
    }
    
    public Visit VisitDataOnDemand.getRandomVisit() {
        init();
        Visit obj = data.get(rnd.nextInt(data.size()));
        return Visit.findVisit(obj.getId());
    }
    
    public boolean VisitDataOnDemand.modifyVisit(Visit obj) {
        return false;
    }
    
    @Transactional(propagation = Propagation.REQUIRES_NEW)
    public void VisitDataOnDemand.init() {
        if (data != null && !data.isEmpty()) {
            return;
        }
        
        data = com.springsource.petclinic.domain.Visit.findVisitEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Visit' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<com.springsource.petclinic.domain.Visit>();
        for (int i = 0; i < 10; i++) {
            com.springsource.petclinic.domain.Visit obj = getNewTransientVisit(i);
            obj.persist();
            data.add(obj);
        }
    }
    
}
